select * from customer limit 20

-- what is total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer
group by gender;

-- which customers used a discount but still spent more then the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and 
purchase_amount >= (select AVG(purchase_amount) from customer);

-- which are the top 5 products with the highest average review rating?
select item_purchased , round(avg(review_rating::numeric),2) as "Average Product Rating" 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amount between standered and express shipping
select shipping_type, round(AVG(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subsrcibed customers spent more? compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,
	count(customer_id) as total_customers,
	ROUND(AVG(purchase_amount),2) as avg_spend,
	ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend,total_revenue DESC;

-- Which 5 products have highest percentage of purchases with discount applied?
select item_purchased,
	ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
From customer
group by item_purchased
Order by discount_rate desc
limit 5;

-- segment customers into new,returning and loyal based on their total
-- number of previous purchases, and show the count of each segment.
with customer_type as(
 select customer_id, previous_purchases,
 CASE 
 	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases between 2 and 10 THEN 'Returning'
	ELSE 'LOYAL'
	END AS customer_segment
from customer)
select customer_segment, count(*) from customer_type as "number of customers"
group by customer_segment;

-- What are the top 3 most purchased products within each category
with item_counts as(
	select category,
		   item_purchased,
		   count(customer_id) as total_orders,
		   ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) desc) as item_rank
   from customer
   group by category, item_purchased
		   
)
select item_rank, category,item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers (more then 5 previous perchases) alse likely to subscribe?
select subscription_status,
	   count(customer_id) as "repeat customers"
from customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group
select age_group,
       sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
